service: GroceryShopper-backend

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  environment:
    REGION: ${self:provider.region}
    PRODUCTS_TABLE: Products-${self:provider.stage}
    SHOPPING_LIST_TABLE: ShoppingList-${self:provider.stage}
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["ProductsTable", "Arn"] }
        - { "Fn::GetAtt": ["ShoppingListTable", "Arn"] }

functions:
  createProduct:
      handler: products/create.main
      events:
        - http:
            path: products/create
            method: POST

  getProducts:
      handler: products/getAll.main
      events:
        - http:
            path: products/get
            method: GET

  getProduct:
      handler: products/get.main
      events:
        - http:
            path: products/get/{id}
            method: GET

  updateProduct:
      handler: products/update.main
      events:
        - http:
            path: products/update
            method: POST

  deleteProduct:
      handler: products/delete.main
      events:
        - http:
            path: products/delete
            method: DELETE

  addToShoppingList:
      handler: shoppingList/create.main
      events:
        - http:
            path: shoppingList/create
            method: POST

  getProductsFromShoppingList:
      handler: shoppingList/getAll.main
      events:
        - http:
            path: shoppingList/get
            method: GET

  getProductFromShoppingList:
      handler: shoppingList/get.main
      events:
        - http:
            path: shoppingList/get/{id}/{timestamp}
            method: GET

  updateInShoppingList:
      handler: shoppingList/update.main
      events:
        - http:
            path: shoppingList/update
            method: POST

  deleteFromShoppingList:
      handler: shoppingList/delete.main
      events:
        - http:
            path: shoppingList/delete
            method: DELETE

            

resources:
  Resources:
    ProductsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: Products-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ShoppingListTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ShoppingList-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
